# Generated by Django 5.0.4 on 2024-05-19 13:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Integration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('integration_name', models.CharField(max_length=100)),
                ('app_name', models.CharField(max_length=100)),
                ('customer', models.CharField(max_length=100)),
                ('source', models.CharField(max_length=200)),
                ('type', models.CharField(max_length=100)),
                ('apk_file', models.CharField(max_length=5000)),
                ('sh_script', models.CharField(max_length=5000)),
                ('is_active', models.BooleanField(default=True)),
                ('integration_date', models.DateTimeField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Integration_Account',
            fields=[
                ('driver_id', models.IntegerField(primary_key=True, serialize=False)),
                ('login', models.CharField()),
                ('password', models.CharField()),
                ('integration', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.integration')),
            ],
        ),
    ]
