# Generated by Django 5.0.4 on 2024-05-17 07:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Integration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('integration_name', models.CharField(max_length=200)),
                ('customer', models.CharField(max_length=200)),
                ('source', models.CharField(max_length=500)),
                ('type', models.CharField(max_length=100)),
                ('apk_file', models.CharField(max_length=5000)),
                ('sh_script', models.CharField(max_length=5000)),
                ('is_active', models.BooleanField(default=True)),
                ('integration_date', models.DateTimeField(default=datetime.datetime(2024, 5, 17, 7, 8, 22, 968656, tzinfo=datetime.timezone.utc))),
            ],
        ),
    ]
