# Generated by Django 5.0.4 on 2024-05-15 17:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Integration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('integration_name', models.CharField(max_length=200)),
                ('customer', models.CharField(max_length=200)),
                ('driver_id', models.IntegerField()),
                ('source', models.CharField(max_length=500)),
                ('apk_file', models.CharField(max_length=5000)),
                ('sh_script', models.CharField(max_length=5000)),
                ('is_active', models.BooleanField(default=True)),
                ('integration_date', models.DateField(default=datetime.datetime.now)),
            ],
        ),
    ]
