# Generated by Django 5.0.4 on 2024-05-21 16:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
        ('sources', '0002_remove_source_id_alter_source_source_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='integration',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sources.source'),
        ),
    ]
