# Generated by Django 5.0.4 on 2024-05-21 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_integration_source'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='integration_account',
            name='id',
        ),
        migrations.AlterField(
            model_name='integration_account',
            name='driver_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='integration_account',
            name='login',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='integration_account',
            name='password',
            field=models.CharField(),
        ),
    ]
