# Generated by Django 5.0.4 on 2024-06-02 15:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_remove_integration_account_id_and_more'),
        ('sources', '0002_remove_source_id_alter_source_source_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='integration',
            name='source',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sources.source'),
        ),
    ]
