# Generated by Django 5.0.4 on 2024-05-20 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=100)),
                ('operation', models.CharField(max_length=50)),
                ('operation_date', models.CharField(max_length=100)),
            ],
        ),
    ]
