# Generated by Django 5.0.4 on 2024-05-20 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='operation_date',
            field=models.DateTimeField(),
        ),
    ]
