# Generated by Django 5.0.4 on 2024-05-21 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='source',
            name='id',
        ),
        migrations.AlterField(
            model_name='source',
            name='source_name',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
    ]
