# Generated by Django 5.0.4 on 2024-06-08 08:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0004_alter_integration_source'),
    ]

    operations = [
        migrations.CreateModel(
            name='Steps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_number', models.IntegerField()),
                ('action', models.CharField(choices=[('TYP', 'TYPE IN'), ('TAP', 'TAP'), ('SEL', 'SELECT')], max_length=3)),
                ('img', models.ImageField(upload_to='steps/media')),
                ('input_value', models.CharField(blank=True, max_length=128, null=True)),
                ('integration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.integration')),
            ],
        ),
    ]
