# Generated by Django 5.0.4 on 2024-06-08 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('steps', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='steps',
            name='action',
            field=models.CharField(choices=[('TYP', 'TYPE IN'), ('TAP', 'TAP'), ('SEL', 'SELECT')], max_length=10),
        ),
    ]
