# Generated by Django 5.0.4 on 2024-06-08 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('steps', '0002_alter_steps_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='steps',
            name='img',
            field=models.ImageField(upload_to='steps'),
        ),
    ]
