# Generated by Django 5.0.4 on 2024-06-09 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('steps', '0003_alter_steps_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='steps',
            name='img',
            field=models.ImageField(upload_to=''),
        ),
    ]
